[tool.poetry]
name = "matrix"
version = "0.1.0"
description = ""
authors = ["paul <dev@studiop.page>"]

[tool.poetry.dependencies]
python = "^3.5"
matplotlib = "<=3.3.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
